# Generated by Django 5.2.6 on 2025-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
